language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - ".nvm"
install:
- npm install
script:
- cat <(echo eslint; npm run lint --silent -- --format=json;) | PULL_REQUEST_NUMBER=$TRAVIS_PULL_REQUEST
  node index.js
branches:
  only:
  - master
env:
  global:
  - CI_OWNER: brenoc
  - CI_REPO: code-analysis-bot
  - secure: tZSjH+Tt7zxucQ20+X/Calhw/EC2b3xJEyCqZhNkdpaJiw2kBi2xZzCOdg57jZMIa0hDsjA0AML/3/33IshTpyQCTHbBJhRE0p+eVix8w6oe5L5snlXNLHoWR1gqBgj0SJzDjGu1nV4PCfXOppLfMEQCHLhIjXLEpt0fXB9lvGfrEe0oWOsCvZ3smT77/7VKjdULNxHpnRVo8JDXQEFUa/acenTy2i4W8hCZgbVZZ3rIzF6iHjRvhxxrP6VL/vS6SwCCpSgq7tpX3RIPzXakWTE7bAMNK6sSJcOA6FdKgCNnN+pSbaz9cXjHP5PB5+qkEmPsbNZlz4I/q7FaXUwBVwmlXBszYoZ87s6Vscb8Hf0dyO+drYXtdEOykd1MrPcfJMQXLwBajyzl7L8AwfC2YejI39P8xMpBJRQbqDZOThynK3ro6tL9/l34usThirt/BUGsAjimW6bYrWJh7uIcQ14CI7XXZ2cc6LwE+eGCuXH9kadINaDp6Sqd5q+SHgQSF13ik9R2Ginjg00TAqq1ITbz9wwRrDxpZDfHdVGF5jWSEcyjWRKPxaeftUqM9Z6W+n+Dd1Z9+JXjUinIR2OWlegdMXX/D9+YIJ5M9uWK9MrEppMmhZNi/pvy3/pbblOTRaad5ev5cHsG9k/c3HkulXhJgpf2cmpY6HMTfn26AZU=
